name: optbench-website
on:
  push:
    branches:
      - main
  # so we can manually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install required APT packages
        run: |
          sudo apt install python3 python3-pip
          python3 -m pip install --upgrade pip
          pip install sphinx

      - name: Dereference symlinks
        run: |
          find ./website -type l | while read -r symlink; do
            target=$(readlink -f "$symlink")
            cp --remove-destination "$target" "$symlink"
      
      - name: Build documentation
        run: |
          cd website
          make website
      
      - name: Deploy website
        # if: ${{ github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: ./website
